# -*- conf -*-

font=VictorMono Nerd Font:size=14
font-bold=VictorMono Nerd Font:style=Bold:size=14
font-italic=VictorMono Nerd Font:style=Italic:size=14
font-bold-italic=VictorMono Nerd Font:style=Bold,Italic:size=14
letter-spacing=0
pad=16x16

[environment]

[bell]

[desktop-notifications]
command=notify-send --wait --app-name ${app-id} --icon ${app-id} --category ${category} --urgency ${urgency} --expire-time ${expire-time} --hint STRING:image-path:${icon} --hint BOOLEAN:suppress-sound:${muted} --hint STRING:sound-name:${sound-name} --replace-id ${replace-id} ${action-argument} --print-id -- ${title} ${body}
command-action-argument=--action ${action-name}=${action-label}
close=""
inhibit-when-focused=yes

[scrollback]
lines=1000

[url]
launch=xdg-open ${url}
osc8-underline=url-mode

[mouse]

[touch]

[cursor]
style=block

